on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      destination_environment:
        type: environment
      version:
        description: 'Enter version tag (e.g., v1.0.0) or leave blank to deploy latest from main branch.'
        type: string
  workflow_call:
    inputs:
      destination_environment:
        type: string
      version:
        type: string

jobs:

  deploy:
    name: Account level setup in snowflake
    runs-on: ubuntu-latest
    environment: ${{inputs.destination_environment}}

    env:
      SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
      SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}

    steps:
      - name: Display-Environment
        run: |
          echo Target deployment environment: ${{ inputs.destination_environment }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.version }}

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
      - name: create a common user
        run: |
          ~/bin/snowsql -q 'create user dw_sf_admin password = ${{ secrets.COMMONUSER_PASSWORD }} must_change_password = false; alter user dw_sf_admin set default_warehouse = 'compute_wh';'

      - name: create platform_admin Role
        run: |
          ~/bin/snowsql -q 'create role platform_admin;  grant all on account to platform_admin; grant role platform_admin to user dw_sf_admin; grant role platform_admin to user goud195'
      - name: create  Warehouse
        run: |
          export password: ${{ secrets.COMMONUSER_PASSWORD }}
          ~/bin/snowsql -u dw_sf_admin -q 'create warehouse "platform_wh" warehouse_type = standard warehouse_size = xsmall;'
