on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      destination_environment:
        type: environment
      version:
        description: 'Enter version tag (e.g., v1.0.0) or leave blank to deploy latest from main branch.'
        type: string
  workflow_call:
    inputs:
      destination_environment:
        type: string
      version:
        type: string

jobs:

  deploy:
    name: Account level setup in snowflake
    runs-on: ubuntu-latest
    environment: ${{inputs.destination_environment}}

    env:
      SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
      SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

    steps:
      - name: Display-Environment
        run: |
          echo Target deployment environment: ${{ inputs.destination_environment }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.version }}

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
      - name: create Resource Monitoring
        run: |
          ~/bin/snowsql -q 'create resource monitor platform_rm with credit_quota = 3000  triggers  on 110 percent do suspend_immediate  on 100 percent do suspend  on 80 percent do notify  on 70 percent do notify; alter account set resource_monitor = platform_rm;'
      - name: create a common user
        run: |
          ~/bin/snowsql -q 'create user dw_sf_admin password = ${{ secrets.COMMONUSER_PASSWORD }} must_change_password = false; alter user dw_sf_admin set default_warehouse = 'compute_wh';'
      - name: create platform_admin Role
        run: |
          ~/bin/snowsql -q 'create role platform_admin;  grant all on account to platform_admin; grant role platform_admin to user dw_sf_admin; grant role platform_admin to user ${{ secrets.SNOWFLAKE_USERNAME }};'
      - name: create  Warehouse
        run: |
          ~/bin/snowsql -q 'use role platform_admin; create warehouse platform_wh warehouse_type = standard warehouse_size = xsmall;'
      - name: create public_use_data database and grant all roles to public_use_data database
        run: |
          ~/bin/snowsql -q 'use role platform_admin; create database public_use_data; grant all on database public_use_data to role accountadmin; grant all on database public_use_data to role platform_admin; grant all on database public_use_data to role securityadmin; grant all on database public_use_data to role sysadmin; grant all on database public_use_data to role public;'
      - name: create public warehouse for public_use_data database
        run: |
          ~/bin/snowsql -q 'use role platform_admin; create warehouse public_wh warehouse_type = standard warehouse_size = xsmall; grant all on warehouse public_wh to role accountadmin;'
      - name: create public resource monitoring & attach public resource monitor to public warehouse level
        run: |
          ~/bin/snowsql -q 'create resource monitor public_rm  with credit_quota=5000  triggers on 75 percent do notify on 100 percent do suspend on 110 percent do suspend_immediate; alter warehouse public_wh set resource_monitor = public_rm;'
      - name: create public_use_data_admin_role and grant that role on database
        run: |
          ~/bin/snowsql -q 'use role platform_admin; create role public_use_data_admin_role; grant all on database public_use_data to role public_use_data_admin_role with grant option; grant all on warehouse public_wh to role public_use_data_admin_role with grant option; grant all on resource monitor public_rm to role public_use_data_admin_role with grant option; grant all on all schemas in database public_use_data to role public_use_data_admin_role  with grant option; grant all on future schemas in database public_use_data to role public_use_data_admin_role with grant option; grant all on all tables in database public_use_data to role public_use_data_admin_role with grant option; grant all on future tables in database public_use_data to role public_use_data_admin_role with grant option; grant all on all functions in database public_use_data to role public_use_data_admin_role with grant option; grant all on future functions in database public_use_data to role public_use_data_admin_role  with grant option; grant all on all views in database public_use_data to role public_use_data_admin_role with grant option; grant all on future views in database public_use_data to role  public_use_data_admin_role with grant option; grant all on all procedures in database public_use_data to role public_use_data_admin_role with grant option; grant all on future procedures in database public_use_data to role public_use_data_admin_role with grant option;'
      - name: create user public_use_data_admin and grant public_use_data_admin_role to user
        run: |
          ~/bin/snowsql -q 'use role platform_admin; create user public_use_data_admin password = ${{ secrets.COMMONUSER_PASSWORD }}; grant role public_use_data_admin_role to user public_use_data_admin;'
      - name: create role public_use_data_read role and grant privileges to role
        run: |
          ~/bin/snowsql -q 'use role platform_admin; create role public_use_data_read; grant usage on database public_use_data to role public_use_data_read with grant option; grant usage, operate on warehouse public_wh to role public_use_data_read with grant option; grant usage on all schemas in database public_use_data to role public_use_data_read  with grant option; grant usage on future schemas in database public_use_data to role public_use_data_read with grant option; grant select on all tables in database public_use_data to role public_use_data_read with grant option; grant select on future tables in database public_use_data to role public_use_data_read with grant option; grant usage on all functions in database public_use_data to role public_use_data_read with grant option; grant usage on future functions in database public_use_data to role public_use_data_read  with grant option; grant select on all views in database public_use_data to role public_use_data_read with grant option; grant select on future views in database public_use_data to role  public_use_data_read with grant option; grant usage on all procedures in database public_use_data to role public_use_data_read with grant option; grant usage on future procedures in database public_use_data to role public_use_data_read with grant option;'
      - name: create role public_use_data_write role and grant privileges to role
        run: |
          ~/bin/snowsql -q 'use role platform_admin; create role public_use_data_write; grant all on database public_use_data to role public_use_data_write with grant option; grant usage,operate on warehouse public_wh to role public_use_data_write with grant option; grant all on all schemas in database public_use_data to role public_use_data_write  with grant option; grant all on future schemas in database public_use_data to role public_use_data_write with grant option; grant all on all tables in database public_use_data to role public_use_data_write with grant option; grant all on future tables in database public_use_data to role public_use_data_write with grant option; grant all on all functions in database public_use_data to role public_use_data_write with grant option; grant all on future functions in database public_use_data to role public_use_data_write  with grant option; grant all on all views in database public_use_data to role public_use_data_write with grant option; grant all on future views in database public_use_data to role  public_use_data_write with grant option;'
      - name: create session policyes for Account level
        run: |
          ~/bin/snowsql -q 'use role platform_admin; create database test_session; use database test_session; create session policy platform_session_policy session_idle_timeout_mins = 25 session_ui_idle_timeout_mins = 25; alter account set session policy platform_session_policy;'
      - name: Droping snowflake sample database
        run: |
          ~/bin/snowsql -q 'drop database snowflake_sample_data;'
