name: Snowflake Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Connect to Snowflake
        uses: snowflakedb/snowflake-github-actions@v1
        with:
          account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          user: ${{ secrets.SNOWFLAKE_USER }}
          password: ${{ secrets.SNOWFLAKE_PASSWORD }}
          warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          database: ${{ secrets.SNOWFLAKE_DATABASE }}
          schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
      - name: Create table
        run: |
          snowsql -c ${{ secrets.SNOWFLAKE_CONNECTION }} -f create_table.sql
      - name: Insert data
        run: |
          snowsql -c ${{ secrets.SNOWFLAKE_CONNECTION }} -f insert_data.sql
